nt = int(input('qual tabuada deseja ver? '))
print('Tabuada do: {}'.format(nt))
print(nt * 1)
print(nt * 2)
print(nt * 3)
print(nt * 4)
print(nt * 5)
print(nt * 6)
print(nt * 7)
print(nt * 8)
print(nt * 9)
print(nt * 10)